### ISSUE TITLE
Rucio probe of rucio_report_used_space data stopped

### ISSUE THREAD

**Issue by mrceyhun** [dmwm/CMSRucio#423]
Hi Rucio team,
 
It seems the Rucio probe that sends “rucio_report_used_space” metrics has stopped. Could you please have a look?
https://monit-grafana.cern.ch/d/O7M3h-UMk/rucio-used-space-in-disk-and-tape?orgId=11&viewPanel=3

Probes send data to CMS Monitoring VictoriaMetrics and AFAIK you had to get same alerts to cms-comp-ops-transfer-team .

**Comment by dciangot** [comment]
So, digging a bit by myself, I see this into the probe container currently deployed. I don't know if it is something known already, otherwise I'd ask @ericvaandering or maybe @ivmfnal , if they have any clue. We need anyway to either revert the probe version, or to solve it quite soon.

```
[root@probes-probes-59bb49b6d8-msfmk cms]# jobber test check_report_used_space
Running job "check_report_used_space"...
Job "check_report_used_space" failed.
New status: Good.

Stdout:
Traceback (most recent call last):
  File "/probes/cms/check_report_used_space", line 66, in <module>
    monitor.record_gauge(
AttributeError: module 'rucio.core.monitor' has no attribute 'record_gauge'
```

**Comment by mrceyhun** [comment]
Kind of a breaking change in https://github.com/rucio/rucio/commit/f7fc020e5f1e7f72ccf3b434d5a6fc96ff872cc9

**Comment by mrceyhun** [comment]
It seems you need to start to import MetricManager and use it instead of record_gauge.
This diff shows a hint: https://github.com/rucio/rucio/commit/f7fc020e5f1e7f72ccf3b434d5a6fc96ff872cc9#diff-5f740a1c40c6d9acc1e7387afd40186f5ce8c19b4d046649487a1f9e2ab6045b

**Comment by ericvaandering** [comment]
The probes are supposed to be running Rucio 1.29 but they don't seem to be... Let me fix that.

**Comment by ericvaandering** [comment]
Probes were at 1.29.8.cms2 which actually used Rucio 1.30 underlying code. Downgraded further to 1.29.6.cms2 which seems fine.
